//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shoe
    {
        public int ShoeID { get; set; }
        [Display(Name = "Name")]
        public string ShoeName { get; set; }
        [Display(Name = "Photo URL")]
        public string ShoePicture { get; set; }
        [Display(Name = "Color")]
        public string ShoeColor { get; set; }
        [Display(Name = "Season")]
        public string ShoeSeason { get; set; }
        [Display(Name = "Occasion")]
        public string ShoeOccasion { get; set; }
        public int TypeID { get; set; }
    
        public virtual ClothingType ClothingType { get; set; }
    }
}
