//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wardrobe.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Top
    {
        public int TopID { get; set; }
        [Display(Name = "Name")]
        public string TopName { get; set; }
        [Display(Name = "Photo URL")]
        public string TopPhoto { get; set; }
        [Display(Name = "Color")]
        public string TopColor { get; set; }
        [Display(Name = "Season")]
        public string TopSeason { get; set; }
        public string TopOccasion { get; set; }
        public int TypeID { get; set; }
    
        public virtual ClothingType ClothingType { get; set; }
    }
}
